name: Build Pages

on:
  push:
    branches: ["main", "development" ]
  pull_request:
    branches: ["main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2

    - name: Build docs
      run: |
        poetry install
        poe build-docs

    - name: Commit documentation changes
      run: |
        git clone https://github.com/${{ github.repository }} --branch gh-pages --single-branch gh-pages
        cp -r _build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
